sudo: required
dist: trusty
language: python
python:
- '3.6'
deploy:
  provider: firebase
  token:
    secure: b88LhdFA5vLfZpe+qIuMEFjKUGY3REUTvNOURCz9E8f1a1A8EtwrY5/98hi2wmXrszlSWg36mYUhHqdZDyWRBaHIUZtBQ5JJVTKNGOQYR3Z3bi+GYm90ZFfhKxWmQiAEWNFTBB1MrflGpQVelUN+fDO7S+D5tH0YJj+ruCpTEhA1fXa2DXFw/AXtVZNQNaOFSjj5uoC7ZH9pCDDzkNVetpGm5Bc2Mp7YuK3AKsoAdKNwmpHUadSc3FkWgwlLs/MvKfaSQGgoL6Xi1JL+EFLfEV2Dc8rfJdkIIyLFqhLzs3UU4m5kl44ZeZbGHinHFLV6cgtEOJngg9HgVkGxAaUjmlGDYcrQ7o5px/ZERe9X3+5+Nu3xEen+qRpqoW0qZ3NabWDKzXZMNBOVb0qTX9MPf6zsqkxCv2YsvPNt8AysYmo7NwGtACE3vSQT6IzlpJSSw7z9v88K44IWghJ1vqOo6PEV7moReYkL6jofzXtxYQ7pwGioDX4DCPqVVMgVe8jyvmm2Z60QcUg9t3HrdXLKo+clZ2uWv0QLUi88w26jnwHDZAqMxezM4eoCQz1+PQxjZGu7cfV2zkIi8s6Z04rw5XS+jokIQyErZ2dUE9EBIcAuV/+kUBrlmDMrzev0iMFU5Mv/PkwKcS/Yn161RLBi5krh3Kfgr9U+UOz0ylMXq5w=
  on:
    branch: master
before_script:
- pip install mkdocs
script: mkdocs build